### ISSUE TITLE
Failed to activate the atom-text-transformer package

### ISSUE THREAD

**Issue by nmccready** [jackytsu/atom-text-transformer#2]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-text-transformer](https://github.com/jackytsu/atom-text-transformer) package, v0.4.0

### Stack Trace

Failed to activate the atom-text-transformer package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.activate (/Users/nem/.atom/packages/atom-text-transformer/lib/atom-text-transformer.coffee:26:40)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:446:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:350:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:423:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:625:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:51:25)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Stylus, v0.6.0
atom-color-highlight, v3.0.8
atom-text-transformer, v0.4.0
autoclose-html, v0.15.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.2
autocomplete-snippets, v1.0.1
coffee-compile, v0.11.0
coffee-lint, v0.7.3
color-picker, v1.4.4
command-logger, v0.22.0
hide-files, v0.1.5
highlight-line, v0.10.1
highlight-selected, v0.9.1
html-helper, v0.2.3
indent-guide-ext, v0.1.0
jslint, v1.2.0
language-coffee-script, v0.38.1
language-jade, v0.3.0
language-javascript-semantic, v0.1.0
language-nginx, v0.4.0
language-scala, v1.1.0
language-stylus, v0.1.0
language-syntax-settings, v2.6.0
linter-erb, v0.1.0
linter-scalac, v0.3.3
pain-split, v1.3.1
project-palette-finder, v2.4.16
recent-files, v0.3.0
refactor, v0.4.1
show-in-folder, v0.1.0
svg-preview, v0.5.1
tabular, v0.1.0
view-tail-large-files, v0.1.13

# Dev
No dev packages
```

**Comment by jackytsu** [comment]
fixed in 0.5.0
